"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['app.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    # 'semi_standalone': True,
    'site_packages': True,
    'plist': {
        'CFBundleName': 'Clocks',
        'CFBundleDisplayName': 'Clocks',
        'LSPrefersPPC': True,
        'LSUIElement': True,
    },
    'packages': [
        'pytz',
        'tzlocal',
        'rumps',
    ],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
